
import { User, Job, Application, Notification, UserRole, JobType } from './types';

export const initialUsers: User[] = [
  {
    id: 'user-1',
    username: 'prithvi',
    password: 'password123',
    role: UserRole.Provider,
    email: 'prithvi@gmail.com',
    phone: '9822787847',
    company: 'sutar farms',
    profilePicture: undefined,
    location: 'hupari',
  },
  {
    id: 'user-2',
    username: 'sumit',
    password: 'password123',
    role: UserRole.Seeker,
    email: 'sumit@gmail.com',
    phone: '9191919122',
    description: 'A hungry learner passionate about sustainable agriculture and technology.',
    skills: ['Agronomy', 'Data Analysis', 'Pest Control'],
    profilePicture: undefined,
    location: 'RuralTown, USA',
    favoriteJobs: [],
  },
];

export const initialJobs: Job[] = [
  {
    id: 'job-1',
    providerId: 'user-1',
    title: 'Farm Manager',
    companyName: 'Green Valley Agriculture',
    location: 'RuralTown, USA',
    description: 'Oversee daily operations of a large-scale organic farm. Responsibilities include crop planning, staff management, and ensuring compliance with organic standards.',
    skills: ['Agronomy', 'Team Leadership', 'Organic Farming'],
    jobType: JobType.FullTime,
    postedOn: '2023-09-15T10:00:00Z',
  },
  {
    id: 'job-2',
    providerId: 'user-1',
    title: 'Agritech Specialist',
    companyName: 'AgriFuture Inc.',
    location: 'Farmville, USA',
    description: 'Implement and manage precision agriculture technologies, including drones, GPS systems, and automated irrigation. Analyze data to improve crop yields and resource efficiency.',
    skills: ['Precision Agriculture', 'Data Analysis', 'Drone Operation'],
    jobType: JobType.FullTime,
    postedOn: '2023-09-20T14:30:00Z',
  },
  {
    id: 'job-3',
    providerId: 'user-1',
    title: 'accounting',
    companyName: 'sutar farms',
    location: 'hupari',
    description: 'managing budget and handling accounts of company',
    skills: ['accounting', 'data analysis'],
    jobType: JobType.FullTime,
    postedOn: '2023-10-01T09:00:00Z',
  },
  {
    id: 'job-4',
    providerId: 'user-1',
    title: 'Veterinary Technician',
    companyName: 'CountrySide Vets',
    location: 'Meadowlands, USA',
    description: 'Support veterinarians in a mixed-practice clinic serving both large and small animals. Duties include surgical assistance, lab work, and client communication.',
    skills: ['Animal Handling', 'Veterinary Medicine', 'Client Communication'],
    jobType: JobType.FullTime,
    postedOn: '2023-10-05T11:00:00Z',
  },
  {
    id: 'job-5',
    providerId: 'user-1',
    title: 'Seasonal Harvester',
    companyName: 'Sunny Orchards',
    location: 'Orchard City, USA',
    description: 'Assist with the seasonal harvesting of apples and pears. This is a temporary position with the potential for future opportunities.',
    skills: ['Manual Dexterity', 'Teamwork', 'Punctuality'],
    jobType: JobType.PartTime,
    postedOn: '2023-08-20T08:00:00Z',
  },
  {
    id: 'job-6',
    providerId: 'user-1',
    title: 'Farmers Market Stall Manager',
    companyName: 'Local Roots Cooperative',
    location: 'Marketville, USA',
    description: 'Manage our stall at the weekly farmers market. Responsibilities include setup, sales, customer service, and inventory management.',
    skills: ['Customer Service', 'Sales', 'Inventory Management'],
    jobType: JobType.PartTime,
    postedOn: '2023-09-28T16:00:00Z',
  },
  {
      id: 'job-7',
      providerId: 'user-1',
      title: 'watering',
      companyName: 'sutar farms',
      location: 'hupari',
      description: 'watering the plants at night between 11 pm to 1 am',
      skills: ['Hard working'],
      jobType: JobType.PartTime,
      postedOn: '2023-10-10T18:00:00Z',
  },
  {
      id: 'job-8',
      providerId: 'user-1',
      title: 'Greenhouse Worker',
      companyName: 'Bloom & Grow Nursery',
      location: 'Greenleaf, USA',
      description: 'Care for plants in a commercial greenhouse. Tasks include watering, potting, pest control, and preparing orders for shipment.',
      skills: ['Horticulture', 'Pest Control', 'Attention to Detail'],
      jobType: JobType.PartTime,
      postedOn: '2023-10-12T07:45:00Z',
  }
];

export const initialApplications: Application[] = [];
export const initialNotifications: Notification[] = [];
